### PR TITLE
#166111758 Integrate view all loan application with an existing endpoint

### PR DESCRIPTION
**Pull request by victor-shagor**
#### What does this PR do?
         implement database with getting all loan applications
#### Description of Task to be completed?
          integrate get all loan applications with an existing endpoint
#### How should this be manually tested?
clone the repo and test locally
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166111758](https://www.pivotaltracker.com/story/show/166111758)

### CODE REVIEW

**Review by luqmanoop — COMMENTED** [review]
Did you actually build an endpoint in this PR?

**Comment by victor-shagor** [comment]
no, used the same endpoint with get repaid loans

**Comment by victor-shagor** [comment]
can I edit the title?

**Comment by luqmanoop** [comment]
> can I edit the title?

Yes

**Comment by victor-shagor** [comment]
done.

**Comment by luqmanoop** [comment]
Go ahead and merge

**Comment by victor-shagor** [comment]
okay, thanks

**Pull request merged**
