### PR TITLE
#166180939 implement a test on the get repaid loan response

### PR DESCRIPTION
**Pull request by victor-shagor**
#### What does this PR do?
         implement test to get repaid loan endpoint
#### Description of Task to be completed?
          implent view repaid loan endpoint test 
#### How should this be manually tested?
clone the repo and test locally
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166180939](https://www.pivotaltracker.com/story/show/166180939)
#### Questions:

### CODE REVIEW

**Review by luqmanoop — COMMENTED** [review]
Your PR title and submitted work don't align. 

Can you explain what exactly this PR is doing/supposed to do?

**Comment by victor-shagor** [comment]
I used the same function to  get all repaid loans as well as get all current loans, so all I did in this branch was added to the test

**Comment by luqmanoop** [comment]
If **all** you did was to add the test, I think it's better that the PR title reflects that.

**Comment by victor-shagor** [comment]
okay, understood

**Comment by luqmanoop** [comment]
This also means your Pivotal Tracker (ID) has not been linked to the right ticket.

**Comment by victor-shagor** [comment]
okay will do that right away

**Comment by victor-shagor** [comment]
done

**Comment by luqmanoop** [comment]
Go ahead and merge

**Comment by victor-shagor** [comment]
thanks

**Pull request merged**
